;;; popup-complete-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from popup-complete.el

(autoload 'popup-complete--in-region "popup-complete" "\


(fn NEXT-FUNC START END COLLECTION &optional PREDICATE)")
(add-hook 'completion-in-region-functions 'popup-complete--in-region)
(register-definition-prefixes "popup-complete" '("popup-complete-"))

;;; End of scraped data

(provide 'popup-complete-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; popup-complete-autoloads.el ends here
